version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.7.4
        user: root
    #working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            pwd
            ls -la
            docker run -e DOJOKEY=${DOJOKEY} -e DOJOIP=${DOJOIP} -e PRODNAME='Gronit' --rm  -v "/root/project:/proj"  cyberkru/trufflehog-dojo
            
workflows:
  build_test_deploy:
    jobs:
      - build_test:
          context:
          - Scan_Env
