version: 2.1
jobs:
  sast_scan:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      # - run:
      #     command: |
      #       docker create -v /proj --name appcon alpine:3.4 /bin/true
      #       docker cp . appcon:/proj
      #       docker run -e DOJOKEY=${DOJOKEY} -e DOJOIP=${DOJOIP} -e PRODNAME='Gronit' --rm  --volumes-from appcon  cyberkru/trufflehog-dojo
      - run:
            command: |
              docker create -v /proj --name appcon alpine:3.4 /bin/true
              docker cp . appcon:/proj
              docker run --rm --volumes-from appcon zricethezav/gitleaks:latest detect --source="/proj" || true
              docker ls appcon:/proj
      # - run:
      #       docker run -e SONARTOKEN=${SONARTOKEN} 
      #       -e ORGANIZATION=${SONAR_ORGANIZATION} 
      #       -e COMPONENTKEY=${LENDING_KEY} 
      #       -e DOJOKEY=${DOJOKEY} 
      #       -e DOJOIP=${DOJOIP} 
      #       -e PRODNAME=${LENDING_PRODNAME} 
      #       cyberkru/sonar-report
  
workflows:
  build_test_deploy:
    jobs:
       - sast_scan:
           context:
           - Scan_Env
      
