version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker run -e DOJOKEY=${DOJOKEY} \
              -e DOJOIP=${DOJOIP} \
              -e PRODNAME='Gronit' \
              --rm -u $(id -u):$(id -g) \
              -v `pwd`:'/proj' cyberkru/trufflehog-dojo
      
workflows:
  build_test_deploy:
    jobs:
      - build_test:
          context:
          - Scan_Env
